# mkdocs.yml -- MkDocs configuration, all *.md files relative to docs/

site_name: Förslag för inköp till AD fontes 

theme: 
    name: readthedocs  #readthedocs # material
    highlightjs: true  # only for readthedocs

site_url: https://axelnilsson98.github.io

nav:
    - Förslag 1: sugestion1.md
    - Förslag 2: sugestion2.md
    - Förslag 3: sugestion3.md